apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-rolebinding
subjects:
- kind: ServiceAccount
  name: promtail-serviceaccount
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: promtail-cluster-role
  apiGroup: rbac.authorization.k8s.io
